blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/mariluski23/fuzzierinter/discussions/categories/q-a
    about: Please, ask questions there on the Discussions
